import type { Metadata } from 'next';
import { Geist_Mono, Doto ,Instrument_Serif} from 'next/font/google';
import './globals.css';
import { Providers } from '@/components/providers';
import Navbar from '@/components/navigation/navbar';

const doto = Doto({
	weight: ['400', '500', '700'],
	variable: '--font-doto',
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

const instrumentSerif = Instrument_Serif({
	weight: ['400'],
	variable: '--font-instrument-serif',
});
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${doto.variable} ${geistMono.className} ${instrumentSerif.variable} antialiased font-sans`}>
				<Providers>
					<Navbar />
					{children}
				</Providers>
			</body>
		</html>
	);
}
